import teethAlignmentIcon from "./icons/Alignment.svg";
import rootCanalIcon from "./icons/rootcanal.svg";
import oralHygiene from "./icons/hygiene.svg";
import cosmiticTeethIcon from "./icons/teeth-solid.svg";
import liveAdvisoryIcon from "./icons/LiveAdvisory.svg";
// alginment teeth content
import pdf1 from "./files/file.pdf";
import headingImage from "./images/complementary-consultant.jpg";
import downloadIcon from "./icons/ArrowLineDown.svg";
import serviceDisplay from "./images/alignmentTeethImage.jpg";
import syring from "./icons/Syringe.svg";
// end of alginment teeth content
export const appointments = [
  {
    id: 321,
    Doctor_id: 243,
    user_id: 1,
    Date: "Mon Jan 10 2024 15:00:00 GMT+0200 (Eastern European Standard Time)",
    Service: "Teeth Alignment",
    Status: "Queued",
    location_id: 1,
  },
  {
    id: 322,
    Doctor_id: 244,
    user_id: 2,
    Date: "Tue Jan 11 2024 14:30:00 GMT+0200 (Eastern European Standard Time)",
    Service: "Eye Examination",
    Status: "Queued",
    location_id: 2,
  },
  {
    id: 323,
    Doctor_id: 245,
    user_id: 3,
    Date: "Wed Jan 12 2024 16:45:00 GMT+0200 (Eastern European Standard Time)",
    Service: "Physical Checkup",
    Status: "Done",
    location_id: 3,
  },
  {
    id: 324,
    Doctor_id: 246,
    user_id: 4,
    Date: "Thu Jan 13 2024 11:15:00 GMT+0200 (Eastern European Standard Time)",
    Service: "Dental Cleaning",
    Status: "Canceled",
    location_id: 1,
  },
  {
    id: 325,
    Doctor_id: 247,
    user_id: 5,
    Date: "Fri Jan 14 2024 13:30:00 GMT+0200 (Eastern European Standard Time)",
    Service: "Flu Vaccination",
    Status: "Queued",
    location_id: 2,
  },
  {
    id: 326,
    Doctor_id: 248,
    user_id: 1,
    Date: "Mon Jan 17 2024 10:00:00 GMT+0200 (Eastern European Standard Time)",
    Service: "Blood Test",
    Status: "Queued",
    location_id: 3,
  },
  {
    id: 327,
    Doctor_id: 249,
    user_id: 2,
    Date: "Tue Jan 18 2024 14:45:00 GMT+0200 (Eastern European Standard Time)",
    Service: "X-ray",
    Status: "Queued",
    location_id: 1,
  },
  {
    id: 328,
    Doctor_id: 250,
    user_id: 3,
    Date: "Wed Jan 19 2024 12:30:00 GMT+0200 (Eastern European Standard Time)",
    Service: "Mental Health Consultation",
    Status: "Queued",
    location_id: 2,
  },
  {
    id: 329,
    Doctor_id: 251,
    user_id: 4,
    Date: "Thu Jan 20 2024 16:00:00 GMT+0200 (Eastern European Standard Time)",
    Service: "Skin Checkup",
    Status: "Queued",
    location_id: 3,
  },
  {
    id: 330,
    Doctor_id: 252,
    user_id: 5,
    Date: "Fri Jan 21 2024 11:45:00 GMT+0200 (Eastern European Standard Time)",
    Service: "Physical Therapy",
    Status: "Queued",
    location_id: 1,
  },
  {
    id: 321,
    Doctor_id: 243,
    user_id: 1,
    Date: "Mon Jan 10 2024 15:00:00 GMT+0200 (Eastern European Standard Time)",
    Service: "Teeth Alignment",
    Status: "Queued",
    location_id: 1,
  },
  {
    id: 322,
    Doctor_id: 244,
    user_id: 2,
    Date: "Tue Jan 11 2024 14:30:00 GMT+0200 (Eastern European Standard Time)",
    Service: "Eye Examination",
    Status: "Queued",
    location_id: 2,
  },
  {
    id: 323,
    Doctor_id: 245,
    user_id: 3,
    Date: "Wed Jan 12 2024 16:45:00 GMT+0200 (Eastern European Standard Time)",
    Service: "Physical Checkup",
    Status: "Done",
    location_id: 3,
  },
  {
    id: 324,
    Doctor_id: 246,
    user_id: 4,
    Date: "Thu Jan 13 2024 11:15:00 GMT+0200 (Eastern European Standard Time)",
    Service: "Dental Cleaning",
    Status: "Canceled",
    location_id: 1,
  },
  {
    id: 325,
    Doctor_id: 247,
    user_id: 5,
    Date: "Fri Jan 14 2024 13:30:00 GMT+0200 (Eastern European Standard Time)",
    Service: "Flu Vaccination",
    Status: "Queued",
    location_id: 2,
  },
  {
    id: 326,
    Doctor_id: 248,
    user_id: 1,
    Date: "Mon Jan 17 2024 10:00:00 GMT+0200 (Eastern European Standard Time)",
    Service: "Blood Test",
    Status: "Queued",
    location_id: 3,
  },
  {
    id: 327,
    Doctor_id: 249,
    user_id: 2,
    Date: "Tue Jan 18 2024 14:45:00 GMT+0200 (Eastern European Standard Time)",
    Service: "X-ray",
    Status: "Queued",
    location_id: 1,
  },
  {
    id: 328,
    Doctor_id: 250,
    user_id: 3,
    Date: "Wed Jan 19 2024 12:30:00 GMT+0200 (Eastern European Standard Time)",
    Service: "Mental Health Consultation",
    Status: "Queued",
    location_id: 2,
  },
  {
    id: 329,
    Doctor_id: 251,
    user_id: 4,
    Date: "Thu Jan 20 2024 16:00:00 GMT+0200 (Eastern European Standard Time)",
    Service: "Skin Checkup",
    Status: "Queued",
    location_id: 3,
  },
  {
    id: 330,
    Doctor_id: 252,
    user_id: 5,
    Date: "Fri Jan 21 2024 11:45:00 GMT+0200 (Eastern European Standard Time)",
    Service: "Physical Therapy",
    Status: "Queued",
    location_id: 1,
  },
  {
    id: 321,
    Doctor_id: 243,
    user_id: 1,
    Date: "Mon Jan 10 2024 15:00:00 GMT+0200 (Eastern European Standard Time)",
    Service: "Teeth Alignment",
    Status: "Queued",
    location_id: 1,
  },
  {
    id: 322,
    Doctor_id: 244,
    user_id: 2,
    Date: "Tue Jan 11 2024 14:30:00 GMT+0200 (Eastern European Standard Time)",
    Service: "Eye Examination",
    Status: "Queued",
    location_id: 2,
  },
  {
    id: 323,
    Doctor_id: 245,
    user_id: 3,
    Date: "Wed Jan 12 2024 16:45:00 GMT+0200 (Eastern European Standard Time)",
    Service: "Physical Checkup",
    Status: "Done",
    location_id: 3,
  },
  {
    id: 324,
    Doctor_id: 246,
    user_id: 4,
    Date: "Thu Jan 13 2024 11:15:00 GMT+0200 (Eastern European Standard Time)",
    Service: "Dental Cleaning",
    Status: "Canceled",
    location_id: 1,
  },
  {
    id: 325,
    Doctor_id: 247,
    user_id: 5,
    Date: "Fri Jan 14 2024 13:30:00 GMT+0200 (Eastern European Standard Time)",
    Service: "Flu Vaccination",
    Status: "Queued",
    location_id: 2,
  },
  {
    id: 326,
    Doctor_id: 248,
    user_id: 1,
    Date: "Mon Jan 17 2024 10:00:00 GMT+0200 (Eastern European Standard Time)",
    Service: "Blood Test",
    Status: "Queued",
    location_id: 3,
  },
  {
    id: 327,
    Doctor_id: 249,
    user_id: 2,
    Date: "Tue Jan 18 2024 14:45:00 GMT+0200 (Eastern European Standard Time)",
    Service: "X-ray",
    Status: "Queued",
    location_id: 1,
  },
  {
    id: 328,
    Doctor_id: 250,
    user_id: 3,
    Date: "Wed Jan 19 2024 12:30:00 GMT+0200 (Eastern European Standard Time)",
    Service: "Mental Health Consultation",
    Status: "Queued",
    location_id: 2,
  },
  {
    id: 329,
    Doctor_id: 251,
    user_id: 4,
    Date: "Thu Jan 20 2024 16:00:00 GMT+0200 (Eastern European Standard Time)",
    Service: "Skin Checkup",
    Status: "Queued",
    location_id: 3,
  },
  {
    id: 330,
    Doctor_id: 252,
    user_id: 5,
    Date: "Fri Jan 21 2024 11:45:00 GMT+0200 (Eastern European Standard Time)",
    Service: "Physical Therapy",
    Status: "Queued",
    location_id: 1,
  },
];
export const services = [
  {
    id: 423,
    Name: "Alignment Teeth",
    icon: teethAlignmentIcon,
    link: "/services/Alignment-teeth",
  },
  {
    id: 453,
    Name: "Root Canal",
    icon: rootCanalIcon,
    link: "/services/root-canal",
  },
  {
    id: 58,
    Name: "Cosmetic teeth",
    icon: cosmiticTeethIcon,
    link: "/services/cosmetic-teeth",
  },
  {
    id: 35,
    Name: "Oral Hygiene",
    icon: oralHygiene,
    link: "/services/oral-hygiene",
  },
  {
    id: 55,
    Name: "Live Advisory",
    icon: liveAdvisoryIcon,
    link: "/services/live-advisory",
  },
];
export const users = [
  {
    id: 1,
    UserName: "omar mahdy",
    roles: [1, 2, 3],
    Image: require("./images/pfp.jpg"),
    Age: 20,
    PhoneNumber: "+00201029949333",
    Email: "omarmahdy@gmail.com",
    Address: "Tanta, El-Gharbia, Egypt",
    City: "Tanta",
    State_Country: "Egypt",
    Postcode: 12345,
    DateOfBirth: "12Th Nov 2003",
    Insurance: {
      // add more details later
      CompanyName: "Insuance Company Name",
      Notes: "this is notes on the insurance company i use.",
    },
    Appointments: {
      Done: [],
      Queued: [321],
    },
  },
  {
    id: 2,
    UserName: "ahmed ali",
    roles: [1, 2, 3],
    Image: require("./images/pfp.jpg"),
    Age: 20,
    PhoneNumber: "+00201029949333",
    Email: "omarmahdy@gmail.com",
    Address: "Tanta, El-Gharbia, Egypt",
    City: "Tanta",
    State_Country: "Egypt",
    Postcode: 12345,
    DateOfBirth: "12Th Nov 2003",
    Insurance: {
      // add more details later
      CompanyName: "Insuance Company Name",
      Notes: "this is notes on the insurance company i use.",
    },
    Appointments: {
      Done: [],
      Queued: [321],
    },
  },
  {
    id: 3,
    UserName: "mohamed tarek",
    roles: [1, 2, 3],
    Image: require("./images/pfp.jpg"),
    Age: 20,
    PhoneNumber: "+00201029949333",
    Email: "omarmahdy@gmail.com",
    Address: "Tanta, El-Gharbia, Egypt",
    City: "Tanta",
    State_Country: "Egypt",
    Postcode: 12345,
    DateOfBirth: "12Th Nov 2003",
    Insurance: {
      // add more details later
      CompanyName: "Insuance Company Name",
      Notes: "this is notes on the insurance company i use.",
    },
    Appointments: {
      Done: [],
      Queued: [321],
    },
  },
  {
    id: 4,
    UserName: "khaled mohamed",
    roles: [1, 2, 3],
    Image: require("./images/pfp.jpg"),
    Age: 20,
    PhoneNumber: "+00201029949333",
    Email: "omarmahdy@gmail.com",
    Address: "Tanta, El-Gharbia, Egypt",
    City: "Tanta",
    State_Country: "Egypt",
    Postcode: 12345,
    DateOfBirth: "12Th Nov 2003",
    Insurance: {
      // add more details later
      CompanyName: "Insuance Company Name",
      Notes: "this is notes on the insurance company i use.",
    },
    Appointments: {
      Done: [],
      Queued: [321],
    },
  },
  {
    id: 5,
    UserName: "mahmoud abdallah",
    roles: [1, 2, 3],
    Image: require("./images/pfp.jpg"),
    Age: 20,
    PhoneNumber: "+00201029949333",
    Email: "omarmahdy@gmail.com",
    Address: "Tanta, El-Gharbia, Egypt",
    City: "Tanta",
    State_Country: "Egypt",
    Postcode: 12345,
    DateOfBirth: "12Th Nov 2003",
    Insurance: {
      // add more details later
      CompanyName: "Insuance Company Name",
      Notes: "this is notes on the insurance company i use.",
    },
    Appointments: {
      Done: [],
      Queued: [321],
    },
  },
];
export const Doctors = [
  {
    id: 243,
    FirstName: "Ahmed",
    LastName: "Mohammed",
    Image: "./src/icons/Default_pfp.png",
    Age: 35,
    PhoneNumber: "+00201012345678",
    Email: "AhmedMohammed@gmail.com",
    Address: "Tanta, El-Gharbia, Egypt",
    City: "Tanta",
    State_Country: "Egypt",
    Postcode: 12345,
    DateOfBirth: "12Th Nov 1987",
    Appointments: {
      Done: [],
      Queued: [appointments[0]],
    },
  },
  {
    id: 244,
    FirstName: "Sara",
    LastName: "Ali",
    Image: "./src/icons/Doctor_pfp1.png",
    Age: 40,
    PhoneNumber: "+00201023456789",
    Email: "SaraAli@gmail.com",
    Address: "Cairo, Egypt",
    City: "Cairo",
    State_Country: "Egypt",
    Postcode: 54321,
    DateOfBirth: "8th Jun 1982",
    Appointments: {
      Done: [],
      Queued: [appointments[1]],
    },
  },
  {
    id: 245,
    FirstName: "Mohamed",
    LastName: "Ibrahim",
    Image: "./src/icons/Doctor_pfp2.png",
    Age: 38,
    PhoneNumber: "+00201034567890",
    Email: "MohamedIbrahim@gmail.com",
    Address: "Alexandria, Egypt",
    City: "Alexandria",
    State_Country: "Egypt",
    Postcode: 67890,
    DateOfBirth: "15th Sep 1984",
    Appointments: {
      Done: [],
      Queued: [appointments[2]],
    },
  },
  {
    id: 246,
    FirstName: "Lina",
    LastName: "Youssef",
    Image: "./src/icons/Doctor_pfp3.png",
    Age: 45,
    PhoneNumber: "+00201045678901",
    Email: "LinaYoussef@gmail.com",
    Address: "Luxor, Egypt",
    City: "Luxor",
    State_Country: "Egypt",
    Postcode: 34567,
    DateOfBirth: "21st Apr 1979",
    Appointments: {
      Done: [],
      Queued: [appointments[3]],
    },
  },
  {
    id: 247,
    FirstName: "Khaled",
    LastName: "Ali",
    Image: "./src/icons/Doctor_pfp4.png",
    Age: 42,
    PhoneNumber: "+00201056789012",
    Email: "KhaledAli@gmail.com",
    Address: "Aswan, Egypt",
    City: "Aswan",
    State_Country: "Egypt",
    Postcode: 56789,
    DateOfBirth: "3rd Dec 1980",
    Appointments: {
      Done: [],
      Queued: [appointments[4]],
    },
  },
  {
    id: 248,
    FirstName: "Fatima",
    LastName: "Hassan",
    Image: "./src/icons/Doctor_pfp5.png",
    Age: 37,
    PhoneNumber: "+00201067890123",
    Email: "FatimaHassan@gmail.com",
    Address: "Sharm El Sheikh, Egypt",
    City: "Sharm El Sheikh",
    State_Country: "Egypt",
    Postcode: 45678,
    DateOfBirth: "10th Aug 1985",
    Appointments: {
      Done: [],
      Queued: [appointments[5]],
    },
  },
  {
    id: 249,
    FirstName: "Hassan",
    LastName: "Yassin",
    Image: "./src/icons/Doctor_pfp6.png",
    Age: 39,
    PhoneNumber: "+00201078901234",
    Email: "HassanYassin@gmail.com",
    Address: "Hurghada, Egypt",
    City: "Hurghada",
    State_Country: "Egypt",
    Postcode: 89012,
    DateOfBirth: "27th Jan 1983",
    Appointments: {
      Done: [],
      Queued: [appointments[6]],
    },
  },
  {
    id: 250,
    FirstName: "Nadia",
    LastName: "Farouk",
    Image: "./src/icons/Doctor_pfp7.png",
    Age: 41,
    PhoneNumber: "+00201089012345",
    Email: "NadiaFarouk@gmail.com",
    Address: "Marsa Matrouh, Egypt",
    City: "Marsa Matrouh",
    State_Country: "Egypt",
    Postcode: 90123,
    DateOfBirth: "14th May 1981",
    Appointments: {
      Done: [],
      Queued: [appointments[7]],
    },
  },
  {
    id: 251,
    FirstName: "Youssef",
    LastName: "Abdelaziz",
    Image: "./src/icons/Doctor_pfp8.png",
    Age: 36,
    PhoneNumber: "+00201090123456",
    Email: "YoussefAbdelaziz@gmail.com",
    Address: "Port Said, Egypt",
    City: "Port Said",
    State_Country: "Egypt",
    Postcode: 23456,
    DateOfBirth: "19th Mar 1986",
    Appointments: {
      Done: [],
      Queued: [appointments[8]],
    },
  },
  {
    id: 252,
    FirstName: "Amira",
    LastName: "Mahmoud",
    Image: "./src/icons/Doctor_pfp9.png",
    Age: 43,
    PhoneNumber: "+00201098765432",
    Email: "AmiraMahmoud@gmail.com",
    Address: "Suez, Egypt",
    City: "Suez",
    State_Country: "Egypt",
    Postcode: 65432,
    DateOfBirth: "7th Jul 1979",
    Appointments: {
      Done: [],
      Queued: [appointments[9]],
    },
  },
];
export const Locations = [
  {
    id: 1,
    Name: "First Location",
    Address: "Tanta, El-Gharbia, Egypt",
  },
  // Add 9 more locations with unique ids (2 to 10)
  {
    id: 2,
    Name: "Second Location",
    Address: "Cairo, Egypt",
  },
  {
    id: 3,
    Name: "Third Location",
    Address: "Alexandria, Egypt",
  },
  {
    id: 4,
    Name: "Fourth Location",
    Address: "Luxor, Egypt",
  },
  {
    id: 5,
    Name: "Fifth Location",
    Address: "Aswan, Egypt",
  },
  {
    id: 6,
    Name: "Sixth Location",
    Address: "Sharm El Sheikh, Egypt",
  },
  {
    id: 7,
    Name: "Seventh Location",
    Address: "Hurghada, Egypt",
  },
  {
    id: 8,
    Name: "Eighth Location",
    Address: "Marsa Matrouh, Egypt",
  },
  {
    id: 9,
    Name: "Ninth Location",
    Address: "Port Said, Egypt",
  },
  {
    id: 10,
    Name: "Tenth Location",
    Address: "Suez, Egypt",
  },
];
export const links = [
  {
    id: 0,
    menuName: "home",
    mainLink: "/",
    dropMenu: false,
  },
  {
    id: 1,
    menuName: "services",
    mainLink: "/services",
    dropMenu: [
      {
        id: 0,
        name: "Root Canal",
        link: `/services/root-canal`,
      },
      {
        id: 1,
        name: "Alignment Teeth",
        link: `/services/alignment-teeth`,
      },
      {
        id: 2,
        name: "Cosmetic Teeth",
        link: `/services/cosmetic-teeth`,
      },
      {
        id: 3,
        name: "Oral Hygiene",
        link: `/services/oral-hygiene`,
      },
      {
        id: 4,
        name: "Live Advisory",
        link: `/services/live-advisory`,
      },
      {
        id: 5,
        name: "Cavity Inspection",
        link: `/services/cavity-inspection`,
      },
    ],
  },
  {
    id: 2,
    menuName: "comfort & technology",
    mainLink: "/comfort-and-technology",
    dropMenu: false,
  },
  {
    id: 4,
    menuName: "profile",
    mainLink: "/profile",
    dropMenu: false,
  },
  {
    id: 3,
    menuName: "about us",
    mainLink: "/about-us",
    dropMenu: false,
  },
  {
    id: 5,
    menuName: "FAQ",
    mainLink: "/faq",
    dropMenu: false,
  },
  {
    id: 6,
    menuName: "Schedule Appointment",
    mainLink: "/Appointment",
    dropMenu: false,
  },
];
export const AlignmentTeethControllerData = {
  sections: [
    {
      id: 1,
      title: "Free Smile Verse Consultation",
      description: [
        `At our clinic, we understand the importance of your smile. That's why we're offering a complimentary initial oral health consultation.`,
        `Our dental experts will create a personalized plan for restoring your teeth, utilizing a digital CT scan and a thorough dental examination. Once you're entirely content with the proposed solutions, we'll commence with the treatment. Let us help you achieve the smile of your dreams at Smile Verse!`,
      ],
      img: headingImage,
      subTitle: "WELCOME GIFT FOR NEW PATIENTS",
    },
    {
      id: 2,
      img: serviceDisplay,
      features: [
        {
          icon: syring,
          title: "title",
          description: "this is a brief description",
        },
        {
          icon: syring,
          title: "title",
          description: "this is a brief description",
        },
        {
          icon: syring,
          title: "title",
          description: "this is a brief description",
        },
        {
          icon: syring,
          title: "title",
          description: "this is a brief description",
        },
      ],
    },
    {
      title: "PATIENTS FORMS",
      id: 3,
      files: [
        { title: "Patient Welcome Form", file: pdf1, icon: downloadIcon },
        { title: "Office Policy", file: pdf1, icon: downloadIcon },
        { title: "Hippa Notice Form", file: pdf1, icon: downloadIcon },
      ],
      insurance: {
        title: "INSURANCE",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum ducimus enim harum tempore, odio vitae accusantium adipisci molestias dicta asperiores, corporis iste quod totam expedita laboriosam explicabo. Rerum, enim voluptate.",
      },
      paymentOptions: {
        title: "PAYMENT OPTIONS",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum ducimus enim harum tempore, odio vitae accusantium adipisci molestias dicta asperiores, corporis iste quod totam expedita laboriosam explicabo. Rerum, enim voluptate.",
      },
    },
  ],
};
